// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using midterm_project.Migrations;

#nullable disable

namespace midterm_project.Migrations
{
    [DbContext(typeof(PetDbContext))]
    [Migration("20230812225612_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("midterm_project.Models.Pet", b =>
                {
                    b.Property<int>("PetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PetAge")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PetDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PetSpecies")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShotsAndVaccinations")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Spayed")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.HasKey("PetId");

                    b.ToTable("Pet");
                });
#pragma warning restore 612, 618
        }
    }
}
